---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  attributes:
    citadel:
      access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

platforms:
  - name: ubuntu-12.04

suites:
  - name: server
    run_list:
      - recipe[balanced-fluentd::server]
      - recipe[balanced-fluentd]
    attributes:
      balanced-fluentd:
        services:
          - balanced
          - precog
          - knox
        matches:
          - [10, 'debug', {}]
          - [50, 'copy', {
            'stores': [
              ['file', {}],
              [
                's3', {
                  'AWS_ACCESS_KEY_ID': <%= ENV['AWS_ACCESS_KEY_ID'] %>,
                  'AWS_SECRET_ACCESS_KEY': <%= ENV['AWS_SECRET_ACCESS_KEY'] %>,
                  'S3_BUCKET_NAME': 'balanced-logs',
                  'S3_ENDPOINT': <%= ENV['S3_ENDPOINT'] || 's3-us-west-1.amazonaws.com' %>,
                  'S3_PREFIX': <%= ENV['S3_PREFIX'] || 'fluentd' %>
                }
              ]
#              ['kafka', {
#                  'KAFKA_SERVERS': ['localhost:9200', 'localhost:9201'],
#                  'KAFKA_TOPICS': ['*']
#              }]
            ]
          }]
          - [99, 'archive', {'log_dir': '/tmp'}]
        sources:
          - [20, 'forwarding', {}]
          - [20, 'http', {}]
          - [20, 'syslog', {}]
    driver:
      network:
        - [private_network, {ip: 10.2.3.10}]
        - [forwarded_port, {guest: 24224, host: 24224}]
        - [forwarded_port, {guest: 8888, host: 8888}]

  - name: client
    run_list:
      - recipe[balanced-fluentd::client]
      - recipe[balanced-fluentd]
    attributes:
      balanced-fluentd:
        matches:
#          - [10, 'debug', {}]
          - [99, 'forwarding', {}]
        sources:
          - [20, 'http', {}]
          - [20, 'syslog', {}]
        in_forward:
          servers: ['10.2.3.10']
